language: node_js
node_js:
  - 11
  - 10
install: yarn
before_script:
  - yarn add discordjs/discord.js --peer
jobs:
  include:
    - stage: deploy
      script: bash ./deploy/travis.sh
cache:
  directories:
    - node_modules
sudo: false
